### ISSUE TITLE
Unexpected token and invalid character

### ISSUE THREAD

**Issue by kwekewk** [ckt1031/one-api#1]
**Routine Inspection**

[//]: # (Delete the existing space in the box and fill in x)
+ [x] I confirm that there are no similar issues at present.
+ [x] I confirm that I have upgraded to the latest version.
+ [x] I have read the project's README in full, especially the frequently asked questions section.
+ [x] I understand and am willing to follow up on this issue, assist with testing, and provide feedback.
+ [x] I understand and agree to the content above, and understand that the project maintainer's energy is limited; **issues that do not follow the rules may be ignored or closed directly**.

**Problem Description**

1. 服务返回错误，代码:500: {"error":{"message":"invalid character 'd' looking for beginning of value","type":"one_api_error","param":"","code":"unmarshal_response_body_failed"}} **This happen on many custom endpoint error returned from [Immersive translate](https://github.com/immersive-translate/immersive-translate/)**
2. Unexpected token 'd', "data: {"id"... is not valid JSON **This happen on many custom endpoint error returned from [Immersive translate](https://github.com/immersive-translate/immersive-translate/)**
3. Unexpected token 'd', "data: {"ch"... is not valid JSON [Immersive translate](https://github.com/immersive-translate/immersive-translate/)
4. Error generating title!
Unexpected token 'd', "data: {"ch"... is not valid JSON [BetterChat](https://github.com/ztjhz/BetterChatGPT)
5. So far, I've found just two projects that return errors.

**Reproduction Steps**

1. Start [Poe-server](https://github.com/caoyunzhou/poe-openai-proxy) 
2. Add to one-api
3. Input Key and Endpoint to [Immersive translate](https://github.com/immersive-translate/immersive-translate/) and [BetterChat](https://github.com/ztjhz/BetterChatGPT) return error 3 and 4

**Expected Result**

- Successful for [Immersive translate](https://github.com/immersive-translate/immersive-translate/)
- Generating Title for [BetterChat](https://github.com/ztjhz/BetterChatGPT)
- Normal behavior when using the endpoint directly

**Comment by kwekewk** [comment]
from [chatgpt-in-terminal](https://github.com/xiaoxx970/chatgpt-in-terminal)
```
Background Title auto-generation Error: Expecting value: line 1 column 1 (char 0). Check log 
for more information
```
Perhaps the error occurred because One-API returned a different JSON from OpenAI.

**Comment by ckt1031** [comment]
Let me check
