### ISSUE TITLE
Adding whitelists based on discord community roles

### ISSUE THREAD

**Issue by Em1tSan** [ckt1031/one-api#5]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

It would be great to add support for whitelisting via discord based on roles in the community.

Such a system is actively used in game servers and works well. In our case, whitelists would allow us to filter out unwanted registrations (multi-accounts) thanks to various discord tools like Doble Counter, and in theory implement synchronization with groups within one-api.

Unfortunately, current oauth2 implementations do not prevent users from creating multi-accounts in any way.

Examples:

https://github.com/FAXES/DiscordWhitelist

https://github.com/Stuyk/altv-discord-auth

**应用场景**
The introduction of whitelists via Discord will allow for better moderation of registered users.

Stronger protection against abuse of registrations, compared to oauth2.

It will be possible to manage groups through synchronization with Discord community roles

**Comment by ckt1031** [comment]
Role whitelisting? If so, this will require an actual discord bot for watching the server.

**Comment by ckt1031** [comment]
Completed.
